### ISSUE TITLE
Ferdi 5.6.0 is out

### ISSUE THREAD

**Issue by carstengrimm** [portapps/ferdi-portable#14]
Latest Version has come out at 18. Jul. have been checking for Portapps a few times and we are still behind.

**Comment by VirusBurst** [comment]
Download Ferdi, they have their OWN portable version...

Place the EXE anywhere and launch it, it will create several folder besides the EXE, after that CLOSE!!!
THEN start Portableapps.io Ferdi, goto "Settings => "Advance" tab => "Open Profile Folder" and mark + copy everything!
LAST STEP: Close and start STOCK Ferdi, same as above GOTO Profile Folder, DELETE everything inside (of course you have to close Ferdi first!) and paste your old profile files in it!

After that, Ferdi should start up, update everything inside and it's done! 
Congrats! You updated Ferdi !!!

**Comment by crazy-max** [comment]
@carstengrimm As explained [on this page](https://portapps.io/doc/reporting-issue/): "We are aware of and notified of new application updates. So there’s no need to create an issue to update an application.".
