### ISSUE TITLE
Ferdi has been Discontinued

### ISSUE THREAD

**Issue by secthulhu** [portapps/ferdi-portable#22]
This is more of an FYI than an issue; _Ferdi has been discontinued_. More info is available in this Reddit post:
  https://www.reddit.com/r/getferdi/comments/vlcrqh/ferdi_is_discontinued_check_here_for_more_info/

The recommended fork of the project is Ferdium:
  https://ferdium.org/

However, an intrepid Redditor (u/SquareBottle) took the time to list other alternatives:
https://www.reddit.com/r/getferdi/comments/u2vkl4/best_alternatives_now_that_ferdi_is_gone/

**Comment by crazy-max** [comment]
I will archive this repo and look at creating a new one to support Ferdium per https://github.com/portapps/portapps/issues/295
